### PR TITLE
Fix/stop index warnings

### LINKED ISSUE #27: Investigate non-valid stop-indexes

### PR DESCRIPTION
**Pull request by 1Maxnet1**
Based on how it is used in motis at https://github.com/motis-project/motis/blob/6807368ba30c558427ce8e9b1f22440ccff0a247/src/railviz.cc#L108 I managed to fix the issue, that probably all stop-indexes were invalid. This should not give any issues anymore and allows further testing, whether tripUpdates are generated.

Resolves #27

### CODE REVIEW

File: src/predictors/gtfs-position-tracker.cc [hunk 1]
```diff
@@ -125,28 +125,23 @@ std::vector<nigiri::location> get_stops_for_trip(nigiri::timetable const& timeta
     // Nur Debug-Meldung vor dem Zugriff
     std::cerr << "Versuche Zugriff auf ersten Transport..." << std::endl;
     // Ersten Transport nehmen und dessen Route
-    auto const first_transport = transports[0];
+    const auto [first, second] = transports[0];
```
Comment (Dirtstone) [inline src/predictors/gtfs-position-tracker.cc]: I now the `auto` is easier to use and makes the code not as long. But in our state I would argue to not use `auto`. In my eyes it makes the code a lot more readable

File: src/predictors/gtfs-position-tracker.cc [hunk 2]
```diff
@@ -125,28 +125,23 @@ std::vector<nigiri::location> get_stops_for_trip(nigiri::timetable const& timeta
...
     std::cerr << "Erster Transport erfolgreich gelesen" << std::endl;
     std::cerr << "Größe von transport_route_: " << timetable.transport_route_.size() << std::endl;
     std::cerr << "Versuche Zugriff auf Transport-Route..." << std::endl;
-    auto const route_idx = timetable.transport_route_.at(first_transport.first); // Änderung hier: .first für transport_idx
-    
+    auto const route_idx = timetable.transport_route_.at(first);
```
Comment (Dirtstone) [inline src/predictors/gtfs-position-tracker.cc]: same here

File: src/predictors/gtfs-position-tracker.cc [hunk 3]
```diff
@@ -125,28 +125,23 @@ std::vector<nigiri::location> get_stops_for_trip(nigiri::timetable const& timeta
...
     std::cerr << "Size of timetable.locations_.ids_" << timetable.locations_.ids_.size() << std::endl;
-    for (auto const stop_idx : stop_sequence) {
-        if (stop_idx < timetable.locations_.ids_.size()) {
-          stops.push_back(timetable.locations_.get(nigiri::location_idx_t(stop_idx)));
-        } else {
-          //std::cerr << "Warnung: Ungültiger Stop-Index: " << stop_idx << std::endl;
-          // Hier entsprechende Fehlerbehandlung einfügen
-        }
+    for (auto const location_idx_t : stop_sequence) {
+      auto const stop_idx = nigiri::stop{location_idx_t}.location_idx();
```
Comment (Dirtstone) [inline src/predictors/gtfs-position-tracker.cc]: Same here

**Review by Dirtstone — APPROVED** [review]
