### PR TITLE
fix: If trip update for trip already exists, just add stop update

### LINKED ISSUE #7: What is defined by the timestamp in the database?
For the availability of x-updates it is important how often gtfsrdb fetches the data from the feed and where the timestamp comes from. Therefore it is necessary to check that this interval is not set to high and due to gtfsrdb the availability is bad.

### LINKED ISSUE #34: Number of tripUpdates in output feed is constantly increasing
When consume the tripUpdate feed with GTFSrDB, for each update it reports a bigger number of tripUpdates, which is a very unlikely scenario. So we need to check why it is increasing and what the issue is here.

### PR DESCRIPTION
**Pull request by Dirtstone**

### CODE REVIEW

File: src/predictors/gtfs-position-tracker.cc [hunk 1]
```diff
@@ -47,27 +47,39 @@ void GTFSPositionTracker::predict(
...
+            if (tripUpdateExists && stopTimeUpdateExists) {
               stopTimeUpdate.mutable_departure()->set_time(std::max(current_time, stopTimeUpdate.departure().time()));
+            } else if(tripUpdateExists && !stopTimeUpdateExists) {
+              transit_realtime::TripUpdate* trip_update = entityToUpdate->mutable_trip_update();
+
+              transit_realtime::TripUpdate_StopTimeUpdate* stop_time_update = trip_update->add_stop_time_update();
+              stop_time_update->set_stop_id(location.id_);
+              stop_time_update->mutable_departure()->set_time(current_time);
+
+              std::cerr << "Update trip update" << timetable.locations_.ids_.size() << std::endl;
```
Comment (1Maxnet1) [inline src/predictors/gtfs-position-tracker.cc]: Why std::cerr ?

**Review by 1Maxnet1 — COMMENTED** [review]
Looks good to me, I still need to verify whether it's working.

File: src/predictors/gtfs-position-tracker.cc [hunk 2]
```diff
@@ -22,67 +22,82 @@ void GTFSPositionTracker::predict(
...
-                  if (update.stop_id() == location.id_) {
-                    tripUpdateExists = true;
-                    stopTimeUpdate = update;
-                    break;
-                  }
+        if (distance < 100) {
+          bool tripUpdateExists = false;
+          transit_realtime::TripUpdate* tripUpdateToUpdate;
+          bool stopTimeUpdateExists = false;
+          transit_realtime::TripUpdate_StopTimeEvent* depatureToUpdate;
```
Comment (1Maxnet1) [inline src/predictors/gtfs-position-tracker.cc]: There is a typo:
```suggestion
          transit_realtime::TripUpdate_StopTimeEvent* departureToUpdate;
```

File: src/predictors/gtfs-position-tracker.cc [hunk 3]
```diff
@@ -22,67 +22,82 @@ void GTFSPositionTracker::predict(
...
-            }
+            tripUpdateToUpdate = new_entity->mutable_trip_update();
+            transit_realtime::TripDescriptor* trip = tripUpdateToUpdate->mutable_trip();
+            trip->set_trip_id(tripID);
+            trip->set_route_id(routeID);
+            tripUpdateToUpdate->mutable_vehicle()->set_id(vehicleID);
+          }
 
+          if (!stopTimeUpdateExists){
+            transit_realtime::TripUpdate_StopTimeUpdate* stop_time_update = tripUpdateToUpdate->add_stop_time_update();
```
Comment (1Maxnet1) [inline src/predictors/gtfs-position-tracker.cc:89]: tripUpdate might not be initialized here. Maybe we should check the path where this could happen and handle that case explicitly.

File: src/predictors/gtfs-position-tracker.cc [hunk 4]
```diff
@@ -22,67 +22,82 @@ void GTFSPositionTracker::predict(
...
+            stop_time_update->set_stop_id(location.id_);
+            depatureToUpdate = stop_time_update->mutable_departure();
           }
+          
+          tripUpdateToUpdate->set_timestamp(current_time);
+          depatureToUpdate->set_time(std::max(current_time, depatureToUpdate->time()));
```
Comment (1Maxnet1) [inline src/predictors/gtfs-position-tracker.cc]: depatureToUpdate might not be initialized here. Maybe we should check the path where this could happen and handle that case explicitly.

**Review by 1Maxnet1 — APPROVED** [review]
